version: '3'
services: 

    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      container_name: db
      ports: 
        - '3308:3306'
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mercadinho_gregory
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        TZ: 'America/Sao_Paulo'
    
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    redis-master: 
      image: 'bitnami/redis:latest'
      ports: 
        - "6379:6379"
      environment:
        - REDIS_REPLICATION_MODE=master
        - ALLOW_EMPTY_PASSWORD=yes
      volumes: 
        - 'redis_data:/bitnami'
    
    redis-replica:
      image: 'bitnami/redis:latest'
      ports: 
        - '6389:6389'
      depends_on: 
        - redis-master
      environment: 
        - REDIS_REPLICATION_MODE=slave
        - REDIS_MASTER_HOST=redis-master
        - REDIS_MASTER_PORT_NUMBER=6379
        - ALLOW_EMPTY_PASSWORD=yes

    zookeeper:
      image: bitnami/zookeeper:latest
      ports: 
        - "2181:2181"
      environment: 
        - ALLOW_ANONYMOUS_LOGIN=yes
    
    kafka:
      image: bitnami/kafka:latest
      ports: 
        - "9092:9092"
      expose: 
        - "9093"
      environment: 
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ALLOW_PLAINTEXT_LISTENER: 'yes'
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_CREATE_TOPICS: 'send-pdf-email:1:1'
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on: 
        - zookeeper

volumes: 
  redis_data: